@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYyNzEyMzA2LCJ1c2VySWQiOiI1In0.G1rlUzM_sA8EEiydXYN1PB8LA9-xCUAdYo4NAXL81vM
### Get all ingredients
GET http://localhost:8080/ingredients
Accept: application/json

###

### Get ingredient by ID
GET http://localhost:8080/ingredients/3
Accept: application/json

###

### Get ingredient by name
GET http://localhost:8080/ingredients/name/Apple
Accept: application/json

###

### Create a new ingredient
POST http://localhost:8080/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Banana",
  "description": "A yellow fruit",
  "allergens": []
}

###

### Update an existing ingredient
PUT http://localhost:8080/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "name": "Sugar",
  "description": "Refined sweetener",
  "allergens": ["SULPHITES"]
}

###

### Update allergens for an ingredient
PATCH http://localhost:8080/ingredients/3/allergens
Content-Type: application/json
Authorization: Bearer {{token}}

[
{
  "id": 1,
  "name":"GLUTEN",
  "displayName":"Glutenbevattende granen",
  "description": "Bevat gluten uit tarwe, rogge, gerst, haver, spelt of kamut"
}
]

###

### Delete an ingredient
DELETE http://localhost:8080/ingredients/1
Accept: application/json
Authorization: Bearer {{token}}
###