@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYyNzAxODI4LCJ1c2VySWQiOiIxIn0.XX97EWnLWmuEjAkVq0D4yEHKyfDYK3C5acneuoWKigA

### Get full recipe screen
GET http://127.0.0.1:8080/fullrecipe/1

### Create a new recipe
POST http://localhost:8080/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Spicy Lentil Soup",
  "description": "A hearty and spicy lentil soup perfect for dinner.",
  "prepTime": 10,
  "cookingTime": 30,
  "difficulty": "EASY",
  "image": "spicy_lentil_soup.jpg",
  "mealType": "DINNER",
  "kitchenStyle": "INDIAN",
  "diets": [
    "VEGAN"
  ],
  "ingredients": [
    {
      "ingredient": {
        "name": "Lentils",
        "description": "Hearty and protein-rich lentils",
        "allergens": [],
        "id": 4
      },
      "amount": 0.2,
      "unitType": "KG"
    },
    {
      "ingredient": {
        "name": "Tomatoes",
        "description": "Fresh ripe tomatoes",
        "allergens": [],
        "id": 5
      },
      "amount": 3.0,
      "unitType": "GRAMS"
    },

    {
      "ingredient": {
        "name": "Spices",
        "description": "A mix of Indian spices",
        "allergens": [],
        "id": 6
      },
      "amount": 2.0,
      "unitType": "GRAMS"
    }
  ]
}

### Get all recipes
GET http://localhost:8080/recipes

### Find recipe by title
GET http://localhost:8080/recipes/title/risotto

### Find recipes by difficulty
GET http://localhost:8080/recipes/difficulty/medium

### Find recipes by meal type
GET http://localhost:8080/recipes/mealtype/dinner

### Find recipes by diet
GET http://localhost:8080/recipes/diets/veganistisch

### Find recipes by kitchen style
GET http://localhost:8080/recipes/kitchen/italian

### Get recipe by ID
GET http://127.0.0.1:8080/recipes/1

### Delete recipe by ID
DELETE http://localhost:8080/recipes/1
Content-Type: application/json
Authorization: Bearer {{token}}

### Update recipe
PUT http://localhost:8080/recipes/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Spicy Lentil Soup (Updated)",
  "description": "A hearty and spicy lentil soup perfect for dinner.",
  "prepTime": 20,
  "cookingTime": 40,
  "difficulty": "MEDIUM",
  "image": "spicy_lentil_soup.jpg",
  "mealType": "DINNER",
  "kitchenStyle": "INDIAN",
  "diets": [
    "VEGAN"
  ],
  "ingredients": [
    {
      "ingredient": {
        "name": "Lentils",
        "description": "Hearty and protein-rich lentils",
        "allergens": [],
        "id": 4
      },
      "amount": 0.15,
      "unitType": "KG"
    },
    {
      "ingredient": {
        "name": "Tomatoes",
        "description": "Fresh ripe tomatoes",
        "allergens": [],
        "id": 5
      },
      "amount": 3.5,
      "unitType": "GRAMS"
    },

    {
      "ingredient": {
        "name": "Mixed Spices",
        "description": "A mix of Indian spices",
        "allergens": [],
        "id": 6
      },
      "amount": 2.5,
      "unitType": "GRAMS"
    }
  ]
}


