#Replace token with new token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzY4MjE4NzAzLCJ1c2VySWQiOiJhbGljZUBleGFtcGxlLmNvbSIsInVzZXJOYW1lIjoiQWxpY2UgSm9obnNvbiJ9.Ztx4jHgWPFFlU-xJOGACjJADnWhgIe-_wJ2qW_ZmoJw
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYxMzk4NjY4LCJ1c2VySWQiOiIyIn0.0Js7xIPcglS40m_s6lRpE1hDSXC5_jW9kGiAqNXlQ4A

### get all users
GET http://127.0.0.1:8080/users
Content-Type: application/json
Authorization: Bearer {{token}}
###

### get user with userId 4
GET http://127.0.0.1:8080/users/alice@example.com
Content-Type: application/json
Authorization: Bearer {{token}}
###

### sign in as a user with an admin role
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "pass123"
}
###

### sign in as a user with a user role
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "email": "bart@example.com",
  "password": "admin123"
}
###

### Signup as a new user
POST http://127.0.0.1:8080/signup
Content-Type: application/json

{
  "username": "Bla",
  "password": "Test1",
  "email": "bla@test.nl"

}
###

### check authorization with token
GET http://127.0.0.1:8080/authenticate
Content-Type: application/json
Authorization: Bearer {{token}}
###

### get userid in string for signed in user
GET http://127.0.0.1:8080/secret
Content-Type: application/json
Authorization: Bearer {{token}}
###

### get favorites list from user
GET http://127.0.0.1:8080/users/favourites
Content-Type: application/json
Authorization: Bearer {{token}}

### add or remove a recipe from the favorites list
POST http://127.0.0.1:8080/users/favourites
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "title": "Creamy Mushroom Risotto",
  "description": "A rich and creamy risotto with earthy mushrooms and parmesan.",
  "prepTime": 15,
  "cookingTime": 300,
  "difficulty": "MEDIUM",
  "image": "https://example.com/images/risotto.jpg",
  "mealType": "DINNER",
  "kitchenStyle": "ITALIAN",
  "diets": [
    "VEGAN"
  ],
  "ingredients": [
    {
      "ingredient": {
        "name": "Sugar",
        "description": "A sweet substance",
        "allergens": [],
        "id": 2
      },
      "amount": 50.0,
      "unitType": "GRAMS"
    },
    {
      "ingredient": {
        "name": "Tomatoes",
        "description": "Fresh ripe tomatoes",
        "allergens": [],
        "id": 5
      },
      "amount": 3.0,
      "unitType": "GRAMS"
    }
  ]
}
###

### get the list of ingredients from your "fridge"
GET http://127.0.0.1:8080/users/fridge
Content-Type: application/json
Authorization: Bearer {{token}}

### post favorite item to user
POST http://127.0.0.1:8080/users/fridge
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "name": "Sugar",
  "description": "Refined sweetener",
  "allergens": []
}

### get the list of allergens for signed in user
GET http://127.0.0.1:8080/users/allergens
Content-Type: application/json
Authorization: Bearer {{token}}

### post add or remove allergen for signed in user
POST http://127.0.0.1:8080/users/allergens
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "name": "GLUTEN",
  "displayName": "Glutenbevattende granen",
  "description": "Bevat gluten uit tarwe, rogge, gerst, haver, spelt of kamut"
}

###
GET http://127.0.0.1:8080/fridge
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://127.0.0.1:8080/fridge/add-ingredient-to-fridge
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ingredientName": "Broccoli"
}

###
DELETE http://127.0.0.1:8080/fridge/remove-ingredient-from-fridge
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "ingredientName": "Broccoli"
}

###
GET http://127.0.0.1:8080/favourites
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://127.0.0.1:8080/favourites/add-remove-favourite-recipe
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "recipeId": 2
}