@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYyNzEyMzA2LCJ1c2VySWQiOiI1In0.G1rlUzM_sA8EEiydXYN1PB8LA9-xCUAdYo4NAXL81vM

### Signup as a new user
POST http://127.0.0.1:8080/signup
Content-Type: application/json

{
  "username": "Henk",
  "password": "verysecretpassword",
  "email": "henk@example.com"

}
###

### Signin as a user - put return token on top
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "username": "Henk",
  "email": "henk@example.com",
  "password": "verysecretpassword"
}
###

### get userid in string for signed in user
GET http://127.0.0.1:8080/secret
Content-Type: application/json
Authorization: Bearer {{token}}
###