@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYyNzAxODI4LCJ1c2VySWQiOiIxIn0.XX97EWnLWmuEjAkVq0D4yEHKyfDYK3C5acneuoWKigA

### Signin as a user - put return token on top
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "username": "Henk",
  "email": "henk@example.com",
  "password": "verysecretpassword"
}

###

### get favorites list from user
GET http://127.0.0.1:8080/users/favourites
Content-Type: application/json
Authorization: Bearer {{token}}

### add or remove a recipe from the favorites list
POST http://127.0.0.1:8080/users/favourites
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "title": "Creamy Mushroom Risotto",
  "description": "A rich and creamy risotto with earthy mushrooms and parmesan.",
  "prepTime": 15,
  "cookingTime": 300,
  "difficulty": "MEDIUM",
  "image": "https://example.com/images/risotto.jpg",
  "mealType": "DINNER",
  "kitchenStyle": "ITALIAN",
  "diets": [
    "VEGAN"
  ],
  "ingredients": [
    {
      "ingredient": {
        "name": "Sugar",
        "description": "A sweet substance",
        "allergens": [],
        "id": 2
      },
      "amount": 50.0,
      "unitType": "GRAMS"
    },
    {
      "ingredient": {
        "name": "Tomatoes",
        "description": "Fresh ripe tomatoes",
        "allergens": [],
        "id": 5
      },
      "amount": 3.0,
      "unitType": "GRAMS"
    }
  ]
}
