@auth_token = PASTE_YOUR_VALID_JWT_TOKEN_HERE

### Get all recipes
GET http://localhost:8080/recipes

### Find recipe by title
GET http://localhost:8080/recipes/title/risotto

### Find recipes by difficulty
GET http://localhost:8080/recipes/difficulty/easy

### Find recipes by meal type
GET http://localhost:8080/recipes/mealtype/dinner

### Find recipes by diet
GET http://localhost:8080/recipes/diets/veganistisch

### Find recipes by kitchen style
GET http://localhost:8080/recipes/kitchen/italian

### Find recipes by Ingredient names
POST http://localhost:8080/recipes/ingredient
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Sugar",
  "description": "A sweet substance",
  "allergens": [],
  "id": 2
}

### Upload a new recipe
POST http://localhost:8080/recipes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "My New Recipe",
  "description": "A delicious test recipe",
  "instructions": "Mix ingredients and cook.",
  "prepTime": 15,
  "cookingTime": 30,
  "difficulty": "EASY",
  "mealType": "DINNER",
  "kitchenStyle": "ITALIAN",
  "images": [],
  "diets": [],
  "allergens": [],
  "ingredients": []
}
